# Generated by Django 5.0.4 on 2024-07-19 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='personal',
            old_name='lname',
            new_name='lasrt_name',
        ),
    ]
